// Mock route for downloading files
export async function GET(
  request: Request,
  { params }: { params: { bucket: string; key: string } }
) {
  const { bucket, key } = params;
  
  console.log(`Mock download requested for bucket: ${bucket}, key: ${key}`);
  
  // Determine if it's a MD or ZIP file based on the key
  const isZip = key.endsWith('.zip');
  
  // Create mock content based on the file type
  let content = '';
  let filename = '';
  
  if (isZip) {
    // For ZIP, return a simple text file (since we can't create real ZIP files here)
    content = 'This is a mock ZIP file content. In a real implementation, this would be binary data.';
    filename = 'mock-documentation.zip';
  } else {
    // For MD file, return some markdown content
    content = `# Mock Documentation
    
## Introduction

This is a mock Markdown file generated by OmniDocs Converter.

## Features

- Easy documentation conversion
- Support for multiple formats
- Automatic crawling of documentation sites

## Usage

See the [documentation](https://example.com/docs) for more information.
`;
    filename = 'all_docs.md';
  }
  
  // Set appropriate headers
  const headers = new Headers({
    'Content-Type': isZip ? 'application/zip' : 'text/markdown',
    'Content-Disposition': `attachment; filename="${filename}"`,
  });
  
  return new Response(content, { headers });
} 